language: java
script: mvn test package
jdk:
  - openjdk6
branches:
  only:
    - master
env:
 global:
   - "ARTIFACTS_AWS_REGION=eu-west-1"
   - "ARTIFACTS_S3_BUCKET=github-files"
   - secure: "IjPoym1CpkdGKa0+cpu8dwOf1HN1cXBlW0O4eZctebeGcln3Y3mLqOurkYP1\nE1yHg9pcYdBdILxzGBTGculDjJEg6YmTDA0H8CAfHy09zcCJaKH5hdU51zqb\n5ZQxgwZAzyFJnBLFu11K/LMqXJ/f4oN21LJnhzQbUbPhaq+FEA0="
   - secure: "P/Kg+UGNHv7HAGKz8p9hK79s6fr0A+FRV2pjdOezUU3HMbk41QePpTi4qJnf\na6FwibgXkFItRkUp3mcxoc/dPM1pIweAT2UQ/DvXT5g2HJi2rEXtKmrspNUA\nJtXXDpvoatcoQH7PHbdK1IRuycrIK1xZYqGXoQ62KjRUVadf0hI="
before_script:
   - "gem install travis-artifacts"
after_success:
  - "travis-artifacts upload --path target/jsonformatter.jar --target-path jsonformatter"
